#!/bin/bash

# Usage: labsetup REGISTRY_NS_NAME K8S_CLUSTER_NAME
# Where "REGISTRY_NS_NAME" is the desired IBM Container Service Registry
# namespace name, and "K8S_CLUSTER_NAME" is the name of your Kubernetes cluster.

set -e

NS_NAME=${1}
K8S_NAME=${2}
TMPNAME=labsetup-tmp${RANDOM}
ACCOUNT_SEARCH=${ACCOUNT_SEARCH:-"ibmlab01@us.ibm.com"}
LOG="labsetup.log"

rm -f $LOG

# Make sure we clean-up afterwards
trap clean EXIT
function clean {
    if test -f $LOG ; then
        echo "*** Something went wrong:"
        cat $LOG
    fi
    rm -f ${TMPNAME}*
    echo
}

# Error on missing args
if [[ -z "$1" ]]; then
    echo "Missing required parameter 'REGISTRY_NS_NAME'"
    exit 1
fi

if [[ -z "$2" ]]; then
    echo "Missing required parameter 'K8S_CLUSTER_NAME'"
    exit 1
fi

# Look for required executables
if ! which ibmcloud > /dev/null ; then
    echo "'ibmcloud' command is not installed"
    exit 1
fi

if ! ibmcloud cr > /dev/null 2>&1 ; then
    echo "'cr' plugin is not installed"
    exit 1
fi

if ! ibmcloud ks > /dev/null 2>&1 ; then
    echo "'ks' plugin is not installed"
    exit 1
fi

if ! which kubectl > /dev/null 2>&1 ; then
    echo "'kubectl' is not installed"
    exit 1
fi

# Mac and Linux have different flags for base64
base64=(base64 -w0)
if [[ `uname` == *"Darwin"* ]]; then
    base64=(base64 -b0)
fi

# make sure all plugins are up to date
ibmcloud plugin update --all

# download the lab running tool, just in case people need it
TOOLSURL=https://raw.githubusercontent.com/IBM/knative101/master/workshop/tools
test -x .demoscript || wget -q ${TOOLSURL}/.demoscript && chmod +x .demoscript
test -x demo || wget -q ${TOOLSURL}/demo && chmod +x demo
test -x pods || wget -q ${TOOLSURL}/pods && chmod +x pods

# If running again we need to reset things back to the user's real account
currentaccount=$(ibmcloud target|grep "Account:"|sed "s/.*(//" | sed "s/).*//")
if test -f $HOME/.oldaccount ; then
    if [[ "${currentaccount}" != "$(cat $HOME/.oldaccount)" ]]; then
        echo "Switching back to the original account"
        ibmcloud target -c "$(cat $HOME/.oldaccount)" >> $LOG 2>&1
        currentaccount=$(cat $HOME/.oldaccount)
    fi
fi
echo -n "${currentaccount}" > $HOME/.oldaccount

echo Creating registry namespace: ${NS_NAME} | tee -a $LOG
ibmcloud cr namespace-add ${NS_NAME} >> $LOG 2>&1

echo Creating a registry access token | tee -a $LOG
ibmcloud cr token-add --description "for fibdemo" --readwrite > ${TMPNAME}
token=$(grep Token ${TMPNAME} | grep -v -i identi | sed "s/^[^ ]*\s*\([^ ]*\) *$/\1/g")
token64=$(echo -n "${token}" | ${base64[*]})
rm -f ${TMPNAME}

echo Switching to the IBM account to access the Kubernetes cluster | tee -a $LOG
account=$(ibmcloud account list | grep "${ACCOUNT_SEARCH}" | sed "s/ .*//")
if [[ -z "${account}" ]]; then
    echo "Can't find the '${ACCOUNT_SEARCH}' account"
    exit 1
fi
ibmcloud target -c "${account}" >> $LOG 2>&1

echo Retrieving the Kubernetes cluster configuration: ${K8S_NAME} | tee -a $LOG
ibmcloud config --check-version false
ibmcloud ks cluster-config -s --export "${K8S_NAME}" > ${TMPNAME} || \
    (cat ${TMPNAME} && echo Error getting config && exit 1)
config=$(cat "${TMPNAME}")
$(echo ${config})
rm -f "${TMPNAME}"

# echo "Installing Knative (and Istio)" | tee -a $LOG
# ibmcloud ks cluster-addon-enable knative -y --cluster "${K8S_NAME}"

# echo Switching back the original account | tee -a $LOG
# ibmcloud target -c "${currentaccount}" >> $LOG 2>&1

echo Creating the docker registry secret | tee -a $LOG
kubectl delete secret/ibm-cr-secret >> $LOG 2>&1
kubectl create secret docker-registry ibm-cr-secret \
    --docker-server=https://registry.ng.bluemix.net \
    --docker-username=token --docker-password="${token}" >> $LOG 2>&1

# Create the basic auth Secret
echo Creating the basic user auth secret | tee -a $LOG
sed "s/\(^.*password: *\).*/\1${token64}/" < docker-secret.yaml > ${TMPNAME}
kubectl apply -f ${TMPNAME} >> $LOG 2>&1
rm -f ${TMPNAME}

# Create the ServiceAccount
echo Creating the ServiceAccount | tee -a $LOG
kubectl delete serviceaccount/build-bot >> $LOG 2>&1
kubectl create -f service-account.yaml >> $LOG 2>&1

echo
echo Please export this environment variable to start using Kubernetes:
echo 
echo ${config}

rm -f $LOG # So we don't print it by mistake
